### ISSUE TITLE
Instant Crash

### ISSUE THREAD

**Issue by superjlounge** [medcelerate/FFGLTouchEngine#19] opened 2024-07-12 16:34 UTC
Hello, Thx for building this.
I'm getting a crash millseconds after loading an example .tox file.  I'm on Win 11, Resolume 7.20.1 and also 7.21.0.
I'm using an RTX 4090.
Thx, 
Stuart

**Comment by medcelerate** [comment] 2024-07-13 01:58
Check your resolume log file. Most likely this is to do with one of the older betas referencing something that didn't exist. It should be fixed in latest.

**Comment by superjlounge** [comment] 2024-07-13 13:16
Hmm.. Thx for the reply. 
Here's an excerpt from the log - 

[2024-07-13T13:57:59.908+01:00]   INFO: ra::WinPluginInstance::load: Loading plugin 'C:\Users\StuPC\Documents\RESOLUME PLUGINS\FFGLTouchEngineFX.dll'
[2024-07-13T13:57:59.931+01:00]   INFO: Plugin was successfully loaded.
[2024-07-13T13:57:59.966+01:00]WARNING: Invalid rotation of media type in MF reader setting to 0 degrees.
[2024-07-13T13:58:00.084+01:00]WARNING: Invalid rotation of media type in MF reader setting to 0 degrees.
[2024-07-13T13:58:02.970+01:00]   INFO: Context will be deleted: 
[2024-07-13T13:58:03.102+01:00]   INFO: Close screensetup
[2024-07-13T13:59:49.419+01:00]   INFO: ra::WinPluginInstance::load: Loading plugin 'C:\Users\StuPC\Documents\RESOLUME PLUGINS\FFGLTouchEngine.dll'
[2024-07-13T13:59:49.431+01:00]   INFO: Plugin was successfully loaded.
[2024-07-13T13:59:50.802+01:00]   FFGL: Loading TouchEngine

**Comment by superjlounge** [comment] 2024-07-13 13:16
It then crashes after about 2-4 seconds

**Comment by medcelerate** [comment] 2024-07-13 13:18
This looks like an issue somewhere in your touch designer network. Looks
like there’s some issue with some media you have in there.

**Comment by medcelerate** [comment] 2024-07-13 14:02
Can you upload the tox you are having issues with.

**Comment by superjlounge** [comment] 2024-07-13 14:04
Hey, I’m using the examples you have included?
Thx

**Comment by medcelerate** [comment] 2024-07-13 15:02
Can you let me know the version of the plugin you are using?

**Comment by superjlounge** [comment] 2024-07-13 15:57
V0.2-beta9

**Comment by medcelerate** [comment] 2024-07-13 16:06
Can you open one of the talks examples in touch design, designer, and see
what the top input and top output are named? There was a recent change in
the repository that updated all the examples that would cause this behavior.

**Comment by superjlounge** [comment] 2024-07-13 16:23
in1 out1

**Comment by medcelerate** [comment] 2024-07-13 16:31
What I would recommend is cloning the project and launching it using visual
studio then sending me the line it crashes at. I don’t have windows 11 on
my machine so I’m unsure where the crash is coming from.

**Comment by superjlounge** [comment] 2024-07-20 13:28
Hey, sorry for the delay.
Ive done as you instructed but I am getting loads of errors, missing files.
Visual Studio on the PC is not my forte.
Thx, S

**Comment by medcelerate** [comment] 2024-07-21 14:49
I'm going to see if I can source the cause of this issue.

**Comment by medcelerate** [comment] 2024-07-21 19:44
Ok so I was able to test on Windows 11, make sure you are on the latest **release** build of TouchDesigner. I am seeing the instant crash when I launch with my debuuger, but when I launch normally it is fine. I am noticing that this does not even load the symbols in my debugger so my best guess is that however resolume is trying to load the DLL is causing a failure. I believe this may be an issue in the resolume side as since I don't even see the symbols loading something is happening before any of my code runs.

**Closed by medcelerate** 2024-07-21 19:44 UTC

**Comment by superjlounge** [comment] 2024-07-22 09:22
Ok, so you are thinking it might be a Resolume issue?
