### ISSUE TITLE
Respect min/max/default values

### ISSUE THREAD

**Issue by j4s0n-c** [medcelerate/FFGLTouchEngine#8] opened 2024-07-06 19:18 UTC
Resolume should respect the min/max/default values assigned to the int/float parameters in TouchDesigner. Also drop down menus (ie: blend modes on a Composite TOP) would be bonus points. Lemme get you a ko-fi...

**Comment by medcelerate** [comment] 2024-07-06 19:20
Min and max may not be possible due to how resolume handles parameter construction, in the new commits this may or may not work.

**Comment by j4s0n-c** [comment] 2024-07-07 20:26
latest release v0.2-beta3: int and float parameters do not show up at all now in Resolume. Switch, string, and bool still work.

**Comment by medcelerate** [comment] 2024-07-07 21:12
Odd, I'm testing with that version locally and it appears fine. Please make sure you update your TouchEngine DLL as that may be the cause of the problem.

**Comment by OrdinaireX** [comment] 2024-07-07 23:22
Just wanted to chime in and say I'm running into the same problem with float parameters not showing up. I've used the latest TouchEngine DLL, Running Resolume Avenue 7.19 and TouchDesigner 2023.11760

**Comment by medcelerate** [comment] 2024-07-07 23:24
Could you clarify which if you are using FX or source? Try deleting the
touchengine.dll and getting the latest one from the repo.

**Comment by OrdinaireX** [comment] 2024-07-07 23:42
I'm using source and the demo files provided. The touchengine.dll is coming from [v0.2-beta3.zip]

**Comment by OrdinaireX** [comment] 2024-07-08 00:12
I can confirm that float functionality is working with the setup in [v0.2-beta1.zip]

**Comment by medcelerate** [comment] 2024-07-08 00:20
Ah ok, I think I know what the issue could be.

**Comment by medcelerate** [comment] 2024-07-08 01:08
@OrdinaireX I've made a new build, but I am unable to reproduce the behavior on any of the included tox's as source.

**Comment by OrdinaireX** [comment] 2024-07-08 01:44
Hey the new version works well, thanks!

**Comment by j4s0n-c** [comment] 2024-07-08 04:09
Indeed, newest version is working well. int/float pars are back and showing label instead of par name! min/max/default still seem to be non-functional.

**Comment by medcelerate** [comment] 2024-07-08 12:49
Default should work, min and max use the UI min max and not the clamp
values, but also resolume may not be able to reset the ranges dynamically.

**Comment by medcelerate** [comment] 2024-08-23 14:54
Closing due to limitation on the ffgl sdk.

**Closed by medcelerate** 2024-08-23 14:54 UTC
